Thrust: thrust::iterator_facade::operator-
difference_type
iterator_category
operator*
operator++
operator++
operator+=
operator-
operator--
operator--
operator-=
operator[]
pointer
reference
value_type
operator-()
template<typename Derived, typename Value, typename System, typename Traversal, typename Reference, typename Difference = std::ptrdiff_t> __host__ __device__ Derived thrust::iterator_facade< Derived, Value, System, Traversal, Reference, Difference >::operator- (difference_type n) const
operator- subtracts a given quantity from this iterator_facade and returns a new iterator_facade referring to the element at the given position before this iterator_facade.
Parameters
n The quantity to decrement
Returns
An iterator_facade pointing n elements before this iterator_facade.
References thrust::equal(), thrust::operator!=(), thrust::operator+(), thrust::operator-(), thrust::operator==(), thrust::operator>(), and thrust::operator>=().