thrust: thrust::mr::unsynchronized_pool_resource::release
do_allocate
do_deallocate
get_default_options
release
unsynchronized_pool_resource
unsynchronized_pool_resource
~unsynchronized_pool_resource
release()
template<typename Upstream> void thrust::mr::unsynchronized_pool_resource< Upstream >::release () inline
Releases all held memory to upstream.
References thrust::mr::pool_options::alignment, thrust::get(), and thrust::raw_reference_cast().
Referenced by thrust::mr::unsynchronized_pool_resource< Upstream >::~unsynchronized_pool_resource().