thrust: thrust::mr::disjoint_unsynchronized_pool_resource::~disjoint_unsynchronized_pool_resource
disjoint_unsynchronized_pool_resource
disjoint_unsynchronized_pool_resource
do_allocate
do_deallocate
get_default_options
release
~disjoint_unsynchronized_pool_resource
~disjoint_unsynchronized_pool_resource()
template<typename Upstream, typename Bookkeeper> thrust::mr::disjoint_unsynchronized_pool_resource< Upstream, Bookkeeper >::~disjoint_unsynchronized_pool_resource () inline
Destructor. Releases all held memory to upstream.
References thrust::free(), thrust::operator<(), thrust::mr::operator==(), and thrust::mr::disjoint_unsynchronized_pool_resource< Upstream, Bookkeeper >::release().