Thrust: thrust::iterator_adaptor::base_reference
base
base_reference
base_reference
base_type
iterator_adaptor
iterator_adaptor
base_reference() [2/2]
template<typename Derived, typename Base, typename Value = use_default, typename System = use_default, typename Traversal = use_default, typename Reference = use_default, typename Difference = use_default> __host__ __device__ Base& thrust::iterator_adaptor< Derived, Base, Value, System, Traversal, Reference, Difference >::base_reference () protected
Returns
A mutable reference to the Base iterator this iterator_adaptor adapts.
References thrust::advance(), thrust::iterator_adaptor< Derived, Base, Value, System, Traversal, Reference, Difference >::base(), and thrust::equal().