Thrust: thrust::tuple::swap
operator=
swap
tuple
tuple
tuple
swap()
template<class T0, class T1, class T2, class T3, class T4, class T5, class T6, class T7, class T8, class T9> __host__ __device__ void thrust::tuple< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::swap (tuple< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 > & t)
swap swaps the elements of two tuples.
Parameters
t The other tuple with which to swap.
References thrust::make_tuple(), thrust::operator!=(), thrust::operator<(), thrust::operator<=(), thrust::operator==(), thrust::operator>(), thrust::operator>=(), thrust::swap(), and thrust::tie().