thrust: thrust::device_malloc_allocator< T > Class Template Reference
thrust::device_malloc_allocator< T > Class Template Reference
Memory Management Classes
#include <device_malloc_allocator.h>
Classes
struct rebind
Public Types
typedef T value_type
typedef device_ptr< T > pointer
typedef device_ptr< const T > const_pointer
typedef device_reference< T > reference
typedef device_reference< const T > const_reference
typedef std::size_t size_type
typedef pointer::difference_type difference_type
Public Member Functions
__host__ __device__ device_malloc_allocator ()
__host__ __device__ ~device_malloc_allocator ()
__host__ __device__ device_malloc_allocator (device_malloc_allocator const &)
template<typename U >
__host__ __device__ device_malloc_allocator (device_malloc_allocator< U > const &)
__host__ __device__ pointer address (reference r)
__host__ __device__ const_pointer address (const_reference r)
__host__ pointer allocate (size_type cnt, const_pointer=const_pointer(static_cast< T * >(0)))
__host__ void deallocate (pointer p, size_type cnt)
size_type max_size () const
__host__ __device__ bool operator== (device_malloc_allocator const &)
__host__ __device__ bool operator!= (device_malloc_allocator const &a)
Detailed Description
template<typename T>
class thrust::device_malloc_allocator< T >
device_malloc_allocator is a device memory allocator that employs the device_malloc function for allocation.
See also:
device_malloc
device_ptr
http://www.sgi.com/tech/stl/Allocators.html
Member Typedef Documentation
template<typename T > typedef device_ptr<const T> thrust::device_malloc_allocator< T >::const_pointer
const pointer to allocation, device_ptr<const T>.
template<typename T > typedef device_reference<const T> thrust::device_malloc_allocator< T >::const_reference
const reference to allocated element, device_reference<const T>.
template<typename T > typedef pointer::difference_type thrust::device_malloc_allocator< T >::difference_type
Type of allocation difference, pointer::difference_type.
template<typename T > typedef device_ptr<T> thrust::device_malloc_allocator< T >::pointer
Pointer to allocation, device_ptr<T>.
template<typename T > typedef device_reference<T> thrust::device_malloc_allocator< T >::reference
Reference to allocated element, device_reference<T>.
template<typename T > typedef std::size_t thrust::device_malloc_allocator< T >::size_type
Type of allocation size, std::size_t.
template<typename T > typedef T thrust::device_malloc_allocator< T >::value_type
Type of element allocated, T.
Constructor & Destructor Documentation
template<typename T > __host__ __device__ thrust::device_malloc_allocator< T >::device_malloc_allocator () [inline]
No-argument constructor has no effect.
template<typename T > __host__ __device__ thrust::device_malloc_allocator< T >::~device_malloc_allocator () [inline]
No-argument destructor has no effect.
template<typename T > __host__ __device__ thrust::device_malloc_allocator< T >::device_malloc_allocator (device_malloc_allocator< T > const &) [inline]
Copy constructor has no effect.
template<typename T > template<typename U > __host__ __device__ thrust::device_malloc_allocator< T >::device_malloc_allocator (device_malloc_allocator< U > const &) [inline]
Constructor from other device_malloc_allocator has no effect.
Member Function Documentation
template<typename T > __host__ __device__ pointer thrust::device_malloc_allocator< T >::address (reference r) [inline]
Returns the address of an allocated object.
Returns:
&r.
template<typename T > __host__ __device__ const_pointer thrust::device_malloc_allocator< T >::address (const_reference r) [inline]
Returns the address an allocated object.
Returns:
&r.
template<typename T > __host__ pointer thrust::device_malloc_allocator< T >::allocate (size_type cnt, const_pointer = const_pointer(static_cast<T*>(0))) [inline]
Allocates storage for cnt objects.
Parameters:
cnt The number of objects to allocate.
Returns:
A pointer to uninitialized storage for cnt objects.
Note:
Memory allocated by this function must be deallocated with deallocate.
References thrust::device_malloc_allocator< T >::max_size().
template<typename T > __host__ void thrust::device_malloc_allocator< T >::deallocate (pointer p, size_type cnt) [inline]
Deallocates storage for objects allocated with allocate.
Parameters:
p A pointer to the storage to deallocate.
cnt The size of the previous allocation.
Note:
Memory deallocated by this function must previously have been allocated with allocate.
References thrust::device_free().
template<typename T > size_type thrust::device_malloc_allocator< T >::max_size () const [inline]
Returns the largest value n for which allocate(n) might succeed.
Returns:
The largest value n for which allocate(n) might succeed.
Referenced by thrust::device_malloc_allocator< T >::allocate().
template<typename T > __host__ __device__ bool thrust::device_malloc_allocator< T >::operator!= (device_malloc_allocator< T > const & a) [inline]
Compares against another device_malloc_allocator for inequality.
Returns:
false
References thrust::device_malloc_allocator< T >::operator==().
template<typename T > __host__ __device__ bool thrust::device_malloc_allocator< T >::operator== (device_malloc_allocator< T > const &) [inline]
Compares against another device_malloc_allocator for equality.
Returns:
true
Referenced by thrust::device_malloc_allocator< T >::operator!=().
The documentation for this class was generated from the following file:
device_malloc_allocator.h