thrust: thrust::mr::memory_resource::do_deallocate
allocate
deallocate
do_allocate
do_deallocate
do_is_equal
is_equal
pointer
~memory_resource
do_deallocate()
template<typename Pointer = void *> virtual void thrust::mr::memory_resource< Pointer >::do_deallocate (pointer p, std::size_t bytes, std::size_t alignment) pure virtual
Deallocates memory pointed to by p.
Parameters
p pointer to be deallocated
bytes the size of the allocation. This must be equivalent to the value of bytes that was passed to the allocation function that returned p.
alignment the size of the allocation. This must be equivalent to the value of alignment that was passed to the allocation function that returned p.
Implemented in thrust::mr::disjoint_unsynchronized_pool_resource< Upstream, Bookkeeper >, thrust::mr::unsynchronized_pool_resource< Upstream >, thrust::device_ptr_memory_resource< Upstream >, thrust::device_ptr_memory_resource< device_memory_resource >, and thrust::mr::new_delete_resource.
Referenced by thrust::mr::memory_resource< device_ptr< void > >::deallocate(), thrust::mr::memory_resource< device_ptr< void > >::do_is_equal(), and thrust::mr::memory_resource< device_ptr< void > >::is_equal().