thrust: thrust::mr::disjoint_unsynchronized_pool_resource::do_deallocate
disjoint_unsynchronized_pool_resource
disjoint_unsynchronized_pool_resource
do_allocate
do_deallocate
get_default_options
release
~disjoint_unsynchronized_pool_resource
do_deallocate()
template<typename Upstream, typename Bookkeeper> virtual void thrust::mr::disjoint_unsynchronized_pool_resource< Upstream, Bookkeeper >::do_deallocate (void_ptr p, std::size_t bytes, std::size_t alignment = alignof(max_align_t)) inline virtual
Deallocates memory pointed to by p.
Parameters
p pointer to be deallocated
bytes the size of the allocation. This must be equivalent to the value of bytes that was passed to the allocation function that returned p.
alignment the size of the allocation. This must be equivalent to the value of alignment that was passed to the allocation function that returned p.
Implements thrust::mr::memory_resource< Upstream::pointer >.
References thrust::mr::pool_options::alignment, thrust::mr::pool_options::cache_oversized, thrust::find_if(), thrust::get(), thrust::mr::pool_options::largest_block_size, thrust::lower_bound(), and thrust::mr::pool_options::smallest_block_size.