thrust: thrust::system::cuda::experimental::pinned_allocator< T > Class Template Reference
thrust::system::cuda::experimental::pinned_allocator< T > Class Template Reference
Memory Management Classes
Classes
struct rebind
Public Types
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef std::size_t size_type
typedef std::ptrdiff_t difference_type
Public Member Functions
__host__ __device__ pinned_allocator ()
__host__ __device__ ~pinned_allocator ()
__host__ __device__ pinned_allocator (pinned_allocator const &)
template<typename U >
__host__ __device__ pinned_allocator (pinned_allocator< U > const &)
__host__ __device__ pointer address (reference r)
__host__ __device__ const_pointer address (const_reference r)
__host__ pointer allocate (size_type cnt, const_pointer=0)
__host__ void deallocate (pointer p, size_type cnt)
size_type max_size () const
__host__ __device__ bool operator== (pinned_allocator const &x)
__host__ __device__ bool operator!= (pinned_allocator const &x)
template<typename T>
class thrust::system::cuda::experimental::pinned_allocator< T >
Constructor & Destructor Documentation
template<typename T > __host__ __device__ thrust::system::cuda::experimental::pinned_allocator< T >::pinned_allocator () [inline]
pinned_allocator's null constructor does nothing.
template<typename T > __host__ __device__ thrust::system::cuda::experimental::pinned_allocator< T >::~pinned_allocator () [inline]
pinned_allocator's null destructor does nothing.
template<typename T > __host__ __device__ thrust::system::cuda::experimental::pinned_allocator< T >::pinned_allocator (pinned_allocator< T > const &) [inline]
pinned_allocator's copy constructor does nothing.
template<typename T > template<typename U > __host__ __device__ thrust::system::cuda::experimental::pinned_allocator< T >::pinned_allocator (pinned_allocator< U > const &) [inline]
This version of pinned_allocator's copy constructor is templated on the value_type of the pinned_allocator to copy from. It is provided merely for convenience; it does nothing.
Member Function Documentation
template<typename T > __host__ __device__ pointer thrust::system::cuda::experimental::pinned_allocator< T >::address (reference r) [inline]
This method returns the address of a reference of interest.
r The reference of interest.
Returns:
r's address.
template<typename T > __host__ __device__ const_pointer thrust::system::cuda::experimental::pinned_allocator< T >::address (const_reference r) [inline]
This method returns the address of a const_reference of interest.
r The const_reference of interest.
Returns:
r's address.
template<typename T > __host__ pointer thrust::system::cuda::experimental::pinned_allocator< T >::allocate (size_type cnt, const_pointer = 0) [inline]
This method allocates storage for objects in pinned host memory.
cnt The number of objects to allocate.
Returns:
a pointer to the newly allocated objects.
Note:
This method does not invoke value_type's constructor. It is the responsibility of the caller to initialize the objects at the returned pointer.
References thrust::system::cuda::experimental::pinned_allocator< T >::max_size().
template<typename T > __host__ void thrust::system::cuda::experimental::pinned_allocator< T >::deallocate (pointer p, size_type cnt) [inline]
This method deallocates pinned host memory previously allocated with this pinned_allocator.
p A pointer to the previously allocated memory. cnt The number of objects previously allocated at p.
Note:
This method does not invoke value_type's destructor. It is the responsibility of the caller to destroy the objects stored at p.
References thrust::system::cuda_category().
template<typename T > size_type thrust::system::cuda::experimental::pinned_allocator< T >::max_size (void) const [inline]
This method returns the maximum size of the cnt parameter accepted by the allocate() method.
Returns:
The maximum number of objects that may be allocated by a single call to allocate().
Referenced by thrust::system::cuda::experimental::pinned_allocator< T >::allocate().
template<typename T > __host__ __device__ bool thrust::system::cuda::experimental::pinned_allocator< T >::operator!= (pinned_allocator< T > const & x) [inline]
This method tests this pinned_allocator for inequality to another.
Parameters:
x The other pinned_allocator of interest.
Returns:
This method always returns false.
References thrust::system::cuda::experimental::pinned_allocator< T >::operator==().
template<typename T > __host__ __device__ bool thrust::system::cuda::experimental::pinned_allocator< T >::operator== (pinned_allocator< T > const & x) [inline]
This method tests this pinned_allocator for equality to another.
Parameters:
x The other pinned_allocator of interest.
Returns:
This method always returns true.
Referenced by thrust::system::cuda::experimental::pinned_allocator< T >::operator!=().
The documentation for this class was generated from the following file:
pinned_allocator.h