thrust: thrust::complex::complex< T >
complex
complex
complex
complex
complex
complex
complex
imag
imag
imag
imag
operator std::complex< T >
operator*=
operator*=
operator+=
operator+=
operator-=
operator-=
operator/=
operator/=
operator=
operator=
operator=
operator=
operator=
real
real
real
real
value_type
operator std::complex< T >()
template<typename T> __host__ thrust::complex< T >::operator std::complex< T > () const inline
Casts this complex to a std::complex of the same type.
References thrust::abs(), thrust::acos(), thrust::acosh(), thrust::arg(), thrust::asin(), thrust::asinh(), thrust::atan(), thrust::atanh(), thrust::conj(), thrust::cos(), thrust::cosh(), thrust::exp(), thrust::log(), thrust::log10(), thrust::norm(), thrust::operator*(), thrust::operator+(), thrust::operator-(), thrust::operator/(), thrust::operator==(), thrust::operator>>(), thrust::polar(), thrust::pow(), thrust::proj(), thrust::sin(), thrust::sinh(), thrust::sqrt(), thrust::tan(), and thrust::tanh().